---
abstract: 'POE eris message dispatcher'
author:
  - 'Brad Lhotsky <brad.lhotsky@gmail.com>'
build_requires:
  English: 0
  Pod::Coverage::TrustPod: 0
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.110440'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-eris
requires:
  POE: 0
  POE::Component::Server::TCP: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/reyjrar/POE-Component-Server-eris.git
version: 0.1
